DIR1="logs"
# DIR2="models"
DIR3="pies"
DIR4="pies/cifar10"
DIR6="pies/cifar10/SupCon"
DIR7="pies/cifar10/SupCon/0.3"
DIR8="pies/cifar10/SupCon/0.5"
DIR9="pies/cifar10/SupCon/0.7"
DIR10="pies/cifar10/SupCon/0.9"
DIR11="pies/cifar10/SupCon/pies_distribution/"
DIR12="pies/cifar10/SupCon/prediction_depth/"
DIR13="pies/cifar10/SupCon/prediction_depth/SupCon/"
DIR14="pies/cifar10/SupCon/prediction_depth/SupCon/CIFAR10/"
DIR15="pies/cifar10/SupCon/prediction_depth/Supervised/"
DIR16="pies/cifar10/SupCon/prediction_depth/Supervised/CIFAR10/"
DIR17="pies/cifar10/SupCon/q_score/"
DIR18="pies/cifar10/SupCon/pies_distribution/"

DIR19="pies/cifar10/supervised"
DIR20="pies/cifar10/supervised/0.3"
DIR21="pies/cifar10/supervised/0.5"
DIR22="pies/cifar10/supervised/0.7"
DIR23="pies/cifar10/supervised/0.9"
DIR24="pies/cifar10/supervised/pies_distribution/"
DIR25="pies/cifar10/supervised/prediction_depth/"
DIR26="pies/cifar10/supervised/prediction_depth/supervised/"
DIR27="pies/cifar10/supervised/prediction_depth/supervised/CIFAR10/"
DIR28="pies/cifar10/supervised/prediction_depth/Supervised/"
DIR29="pies/cifar10/supervised/prediction_depth/Supervised/CIFAR10/"
DIR30="pies/cifar10/supervised/q_score/"
DIR31="pies/cifar10/supervised/pies_distribution/"

[ ! -d "$DIR1" ] && mkdir -p "$DIR1"
# [ ! -d "$DIR2" ] && mkdir -p "$DIR2"
[ ! -d "$DIR3" ] && mkdir -p "$DIR3"
[ ! -d "$DIR4" ] && mkdir -p "$DIR4"
[ ! -d "$DIR6" ] && mkdir -p "$DIR6"
[ ! -d "$DIR7" ] && mkdir -p "$DIR7"
[ ! -d "$DIR8" ] && mkdir -p "$DIR8"
[ ! -d "$DIR9" ] && mkdir -p "$DIR9"
[ ! -d "$DIR10" ] && mkdir -p "$DIR10"
[ ! -d "$DIR11" ] && mkdir -p "$DIR11"
[ ! -d "$DIR12" ] && mkdir -p "$DIR12"
[ ! -d "$DIR13" ] && mkdir -p "$DIR13"
[ ! -d "$DIR14" ] && mkdir -p "$DIR14"
[ ! -d "$DIR15" ] && mkdir -p "$DIR15"
[ ! -d "$DIR16" ] && mkdir -p "$DIR16"
[ ! -d "$DIR17" ] && mkdir -p "$DIR17"
[ ! -d "$DIR18" ] && mkdir -p "$DIR18"
[ ! -d "$DIR19" ] && mkdir -p "$DIR19"
[ ! -d "$DIR20" ] && mkdir -p "$DIR20"
[ ! -d "$DIR21" ] && mkdir -p "$DIR21"
[ ! -d "$DIR22" ] && mkdir -p "$DIR22"
[ ! -d "$DIR23" ] && mkdir -p "$DIR23"
[ ! -d "$DIR24" ] && mkdir -p "$DIR24"
[ ! -d "$DIR25" ] && mkdir -p "$DIR25"
[ ! -d "$DIR26" ] && mkdir -p "$DIR26"
[ ! -d "$DIR27" ] && mkdir -p "$DIR27"
[ ! -d "$DIR28" ] && mkdir -p "$DIR28"
[ ! -d "$DIR29" ] && mkdir -p "$DIR29"
[ ! -d "$DIR30" ] && mkdir -p "$DIR30"
[ ! -d "$DIR31" ] && mkdir -p "$DIR31"